version: '3.5'

services:

  router:
    build: .
    image: stutzlab/mongo-cluster-router
    environment:
      - CONFIG_REPLICA_SET=replica-set1
      - CONFIG_SERVER_NODES=configsrv1,configsrv2,configsrv3
      - SHARD_NAME_PREFIX=shard
      - SHARD_1_NODES=shard1-a,shard1-b
      - SHARD_2_NODES=shard2-a,shard2-b
    ports:
      - 27311:27017

  configsrv1:
    image: stutzlab/mongo-cluster-configsrv
    environment:
      - CONFIG_REPLICA_SET=replica-set1
      - CONFIG_SERVER_NODES=configsrv1,configsrv2,configsrv3
    ports:
      - 27311:27017
